// src/components/QuestionOptions.ts
export const gradeOptions = [
  { value: "grade1", label: "Grade 1" },
  { value: "grade2", label: "Grade 2" },
  { value: "grade3", label: "Grade 3" },
  { value: "grade4", label: "Grade 4" },
  { value: "grade5", label: "Grade 5" },
  { value: "grade6", label: "Grade 6" },
  { value: "grade7", label: "Grade 7" },
  { value: "grade8", label: "Grade 8" },
  { value: "grade9", label: "Grade 9" },
  { value: "grade10", label: "Grade 10" },
  { value: "grade11", label: "Grade 11" },
  { value: "grade12", label: "Grade 12" },
  { value: "other", label: "Other" },
];

export const subjectOptions = [
  { value: "language science", label: "Language Science" },
  { value: "natural science", label: "Natural Science" },
  { value: "social science", label: "Social Science" },
  { value: "other", label: "Other" },
];

export const categoryOptions = [
  { value: "adaptations", label: "Adaptations" },
  { value: "anatomy and physiology", label: "Anatomy and physiology" },
  { value: "astronomy", label: "Astronomy" },
  { value: "atoms and molecules", label: "Atoms and molecules" },
  { value: "cells", label: "Cells" },
  { value: "chemical reactions", label: "Chemical reactions" },
  { value: "climate change", label: "Climate change" },
  { value: "electricity", label: "Electricity" },
  { value: "force and motion", label: "Force and motion" },
  { value: "genes to traits", label: "Genes to traits" },
  { value: "photosynthesis", label: "Photosynthesis" },
  { value: "rocks and minerals", label: "Rocks and minerals" },
  { value: "water cycle", label: "Water cycle" },
  { value: "weather and climate", label: "Weather and climate" },
  { value: "age of exploration", label: "Age of Exploration" },
  { value: "colonial america", label: "Colonial America" },
  { value: "early china", label: "Early China" },
  { value: "early modern europe", label: "Early Modern Europe" },
  { value: "islamic empires", label: "Islamic empires" },
  { value: "the american revolution", label: "The American Revolution" },
  { value: "the civil war", label: "The Civil War" },
  { value: "the silk road", label: "The Silk Road" },
  { value: "world religions", label: "World religions" },
  { value: "author's purpose", label: "Author's purpose" },
  { value: "comprehension strategies", label: "Comprehension strategies" },
  { value: "context clues", label: "Context clues" },
  { value: "literary devices", label: "Literary devices" },
  { value: "poetry elements", label: "Poetry elements" },
  { value: "pronouns", label: "Pronouns" },
  { value: "rhyming", label: "Rhyming" },
  { value: "text structure", label: "Text structure" },
  { value: "editing and revising", label: "Editing and revising" },
  { value: "opinion writing", label: "Opinion writing" },
  { value: "persuasive strategies", label: "Persuasive strategies" },
  { value: "verb tense", label: "Verb tense" },
  { value: "word usage and nuance", label: "Word usage and nuance" },
  { value: "other", label: "Other" },
];

export const topicOptions = [
  { value: "capitalization", label: "Capitalization" },
  { value: "chemistry", label: "Chemistry" },
  { value: "civics", label: "Civics" },
  { value: "culture", label: "Culture" },
  { value: "economics", label: "Economics" },
  { value: "earth-science", label: "Earth Science" },
  { value: "figurative-language", label: "Figurative Language" },
  { value: "global-studies", label: "Global Studies" },
  { value: "grammar", label: "Grammar" },
  { value: "literacy-in-science", label: "Literacy in Science" },
  { value: "phonological-awareness", label: "Phonological Awareness" },
  { value: "physics", label: "Physics" },
  { value: "pronouns", label: "Pronouns" },
  { value: "punctuation", label: "Punctuation" },
  { value: "reading-comprehension", label: "Reading Comprehension" },
  { value: "reference-skills", label: "Reference Skills" },
  {
    value: "science-and-engineering-practices",
    label: "Science and Engineering Practices",
  },
  { value: "units-and-measurement", label: "Units and Measurement" },
  { value: "us-history", label: "US History" },
  { value: "verbs", label: "Verbs" },
  { value: "vocabulary", label: "Vocabulary" },
  { value: "word-study", label: "Word Study" },
  { value: "world-history", label: "World History" },
  { value: "writing-strategies", label: "Writing Strategies" },
  { value: "other", label: "Other" },
];
